variables:
  GIT_STRATEGY: fetch

stages:
  - build
  - test

build:linux:
  image: alpine:latest
  tags:
    - linux
  stage: build
  before_script:
    - apk add --update g++ make cmake linux-headers libcap-dev libuv-dev
  script:
    - make STATIC_LINK=ON
  artifacts:
    paths:
      - "lokinet"

build:freebsd
  tags:
     - fbsd-ci
  stage: build
  script:
    - make
  artifacts:
    paths:
      - "lokint"

#build:windows:
#  tags:
#    - windows
#  stage: build
#  script:
#    - make STATIC_LINK=ON AVX2=OFF JSONRPC=OFF CC=gcc CXX=g++
#  artifacts:
#    paths:
#      - "lokinet.exe"
