language: cpp

os:
  - linux
  - osx

cache: ccache
dist: xenial
osx_image: xcode10.2

compiler:
  - clang
  - gcc

env:
  global:
    - BUILD_TYPE=Release
    - NINJA=ninja
  matrix:
    - STATIC_LINK=OFF
    - STATIC_LINK=OFF SHARED_LIB=ON
    - STATIC_LINK=ON
    - STATIC_LINK=ON SHARED_LIB=ON

addons:
  apt:
    packages:
    - build-essential
    - cmake
    - curl
    - git
    - libcap-dev
    - libuv1-dev
    - ninja-build
  homebrew:
    packages:
    - ccache
    - cmake
    - libuv
    - ninja
    - make

script:
  - PATH="/usr/local/opt/ccache/libexec:$PATH" make test

after_script:
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_COMMIT_LOG
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
      - "chat.freenode.net#llarp"
    nick: lokinet-ci
    template:
      - "%{result} | %{repository}#%{build_number} (%{commit} : %{author}) | Build details : %{build_url}"
