language: cpp

os: windows
  # - linux
  # - osx
  # - windows

cache: ccache
# dist: xenial
# osx_image: xcode10.2

# compiler:
  # - clang
  # - gcc

env:
  global:
    - NINJA=ninja
    - STATIC_LINK=OFF
  matrix:
    - BUILD_TYPE=Debug
    # - BUILD_TYPE=Release

addons:
  apt:
    packages:
    - binutils-gold
    - build-essential
    - cmake
    - curl
    - git
    - libcap-dev
    - libuv1-dev
    - ninja-build
  homebrew:
    packages:
    - ccache
    - cmake
    - libuv
    - ninja
    - make

before_install:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      choco install make ninja;
      choco upgrade cmake cmake.install;
      export CC="/c/Program Files/LLVM/bin/clang-cl";
      export CXX="/c/Program Files/LLVM/bin/clang-cl";
    fi

script:
  - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && make test'

after_script:
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_COMMIT_LOG
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
      - "chat.freenode.net#llarp"
    nick: lokinet-ci
    template:
      - "%{result} | %{repository}#%{build_number} (%{commit} : %{author}) | Build details : %{build_url}"
